CREATE TABLE IF NOT EXISTS users(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id BIGINT UNIQUE,
    username VARCHAR(255) NOT NULL,
    name VARCHAR(155),
    age INTEGER,
    weight REAL,
    height REAL,
    goal_id bigint references nutrition_goals(id),
    created_at TIMESTAMP DEFAULT
    );

create table if not exists workouts(
    id bigint generated by default as identity primary key,
    user_id bigint references users(id),
    workout_date timestamp NOT NUll,
    type varchar(255) NOT NULL,--силовая,кардио,йога
    notes varchar(255) --заметки
);

create table if not exists foods(
    id bigint generated by default as identity primary key,
    food_name varchar(255) NOT NULL,
    calories_cal REAL,
    protein_g REAL,
    fat_g REAL,
    carbohydrates_g REAL,
    date timestamp default CURRENT_TIMESTAMP not null
);

create table if not exists user_foods(
    id bigint generated by default as identity primary key,
    user_id bigint references users(id),
    food_id bigint references foods(id),
    amount real not null,
    date timestamp default CURRENT_TIMESTAMP not null
);

create table if not exists exercises( --справочник упражнений
    id bigint generated by default as identity primary key,
    name varchar(255) NOT NULL,
    muscle_group varchar(255) NOT NULL,
    instructions text,-- описание/инструкция
    equipment varchar--оборудование (штанга/гантели/без)
);

create table if not exists workout_exercises(
    id bigint generated by default as identity primary key,
    workout_id bigint references workouts(id),--какой тип тренировки аля
    exercise_id bigint references EXERCISES(id),--какое упражнение
    sets int, --кол-во подходов
    reps int,--повторения
    weight REAL,
    duration interval --длительность (для кардио)
    check((sets is not null and reps is not null)
    or (duration is not null))
);

create table if not exists nutrition_goals(
    id bigint generated by default as identity primary key,
    user_id bigint references users(id),
    calories real
)