package bot.botStateMachine;

public enum BotState {
    IDLE,
    REG_WAITING_NAME,
    REG_WAITING_AGE,
    REG_WAITING_WEIGHT,
    REG_WAITING_HEIGHT,
    WORKOUT_WAITING_DATE,
    WORKOUT_WAITING_TYPE,
    WORKOUT_WAITING_EXERCISE_NAME,
    WORKOUT_WAITING_REPS,
    WORKOUT_WAITING_SETS,
    WORKOUT_WAITING_EXERCISE_WEIGHT,
    WORKOUT_WAITING_YES_OR_NOT

}
